apiVersion: v1
kind: Pod
metadata:
  name: psql-test
  namespace: edu-maksim-oboznyj

spec:
  restartPolicy: Never

  containers:
    - name: psql
      image: postgres:16
      command:
        - sleep
        - infinity

      volumeMounts:
        - name: postgres-ssl-cert
          mountPath: /root/.postgresql/root.crt
          subPath: root.crt
          readOnly: true

  volumes:
    - name: postgres-ssl-cert
      secret:
        secretName: postgres-ssl-cert
        defaultMode: 384
