apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: django_app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: SECRET_KEY

            - name: DEBUG
              value: "False"

            - name: ALLOWED_HOSTS
              value: "*"

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: DATABASE_URL